/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.Account = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Account model module.
   * @module model/Account
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>Account</code>.
   * A basic representation of a STARFACE account.
   * @alias module:model/Account
   * @class
   * @param accountId {Number} the accountId of the account
   * @param displayInformation {String} the displayInformation of the account
   * @param federationname {String} the federationname of the account
   * @param firstname {String} the firstname of the account
   * @param lastname {String} the lastname of the account
   * @param local {Boolean} the account is not an federation account
   * @param primaryInternalPhoneNumber {String} the primary internal phone number of the account
   * @param type {module:model/Account.TypeEnum} the type of this account
   */
  var exports = function(accountId, displayInformation, federationname, firstname, lastname, local, primaryInternalPhoneNumber, type) {
    var _this = this;

    _this['accountId'] = accountId;
    _this['displayInformation'] = displayInformation;
    _this['federationname'] = federationname;
    _this['firstname'] = firstname;
    _this['lastname'] = lastname;
    _this['local'] = local;
    _this['primaryInternalPhoneNumber'] = primaryInternalPhoneNumber;
    _this['type'] = type;
  };

  /**
   * Constructs a <code>Account</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Account} obj Optional instance to populate.
   * @return {module:model/Account} The populated <code>Account</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accountId')) {
        obj['accountId'] = ApiClient.convertToType(data['accountId'], 'Number');
      }
      if (data.hasOwnProperty('displayInformation')) {
        obj['displayInformation'] = ApiClient.convertToType(data['displayInformation'], 'String');
      }
      if (data.hasOwnProperty('federationname')) {
        obj['federationname'] = ApiClient.convertToType(data['federationname'], 'String');
      }
      if (data.hasOwnProperty('firstname')) {
        obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
      }
      if (data.hasOwnProperty('lastname')) {
        obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
      }
      if (data.hasOwnProperty('local')) {
        obj['local'] = ApiClient.convertToType(data['local'], 'Boolean');
      }
      if (data.hasOwnProperty('primaryInternalPhoneNumber')) {
        obj['primaryInternalPhoneNumber'] = ApiClient.convertToType(data['primaryInternalPhoneNumber'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * the accountId of the account
   * @member {Number} accountId
   */
  exports.prototype['accountId'] = undefined;
  /**
   * the displayInformation of the account
   * @member {String} displayInformation
   */
  exports.prototype['displayInformation'] = undefined;
  /**
   * the federationname of the account
   * @member {String} federationname
   */
  exports.prototype['federationname'] = undefined;
  /**
   * the firstname of the account
   * @member {String} firstname
   */
  exports.prototype['firstname'] = undefined;
  /**
   * the lastname of the account
   * @member {String} lastname
   */
  exports.prototype['lastname'] = undefined;
  /**
   * the account is not an federation account
   * @member {Boolean} local
   */
  exports.prototype['local'] = undefined;
  /**
   * the primary internal phone number of the account
   * @member {String} primaryInternalPhoneNumber
   */
  exports.prototype['primaryInternalPhoneNumber'] = undefined;
  /**
   * the type of this account
   * @member {module:model/Account.TypeEnum} type
   */
  exports.prototype['type'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "USER"
     * @const
     */
    "USER": "USER",
    /**
     * value: "GROUP"
     * @const
     */
    "GROUP": "GROUP",
    /**
     * value: "REMOTE_USER"
     * @const
     */
    "REMOTE_USER": "REMOTE_USER",
    /**
     * value: "REMOTE_GROUP"
     * @const
     */
    "REMOTE_GROUP": "REMOTE_GROUP"  };


  return exports;
}));


