/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.AssignableNumber = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AssignableNumber model module.
   * @module model/AssignableNumber
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>AssignableNumber</code>.
   * A representation of a STARFACE assignableNumber
   * @alias module:model/AssignableNumber
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>AssignableNumber</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AssignableNumber} obj Optional instance to populate.
   * @return {module:model/AssignableNumber} The populated <code>AssignableNumber</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('assigned')) {
        obj['assigned'] = ApiClient.convertToType(data['assigned'], 'Boolean');
      }
      if (data.hasOwnProperty('countryCode')) {
        obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
      }
      if (data.hasOwnProperty('exitCode')) {
        obj['exitCode'] = ApiClient.convertToType(data['exitCode'], 'String');
      }
      if (data.hasOwnProperty('extension')) {
        obj['extension'] = ApiClient.convertToType(data['extension'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('intern')) {
        obj['intern'] = ApiClient.convertToType(data['intern'], 'Boolean');
      }
      if (data.hasOwnProperty('localAreaCode')) {
        obj['localAreaCode'] = ApiClient.convertToType(data['localAreaCode'], 'String');
      }
    }
    return obj;
  }

  /**
   * the assigned option of the assignableNumber
   * @member {Boolean} assigned
   */
  exports.prototype['assigned'] = undefined;
  /**
   * the countryCode of the assignableNumber
   * @member {String} countryCode
   */
  exports.prototype['countryCode'] = undefined;
  /**
   * the exitCode of the assignableNumber
   * @member {String} exitCode
   */
  exports.prototype['exitCode'] = undefined;
  /**
   * the extension of the assignableNumber
   * @member {String} extension
   */
  exports.prototype['extension'] = undefined;
  /**
   * the id of the assignableNumber
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * the intern option of the assignableNumber
   * @member {Boolean} intern
   */
  exports.prototype['intern'] = undefined;
  /**
   * the localAreaCode of the assignableNumber
   * @member {String} localAreaCode
   */
  exports.prototype['localAreaCode'] = undefined;



  return exports;
}));


