/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Attribute'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Attribute'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.Block = factory(root.StarfaceRestApi.ApiClient, root.StarfaceRestApi.Attribute);
  }
}(this, function(ApiClient, Attribute) {
  'use strict';




  /**
   * The Block model module.
   * @module model/Block
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>Block</code>.
   * Collection of attributes in blocks
   * @alias module:model/Block
   * @class
   * @param attributes {Array.<module:model/Attribute>} 
   */
  var exports = function(attributes) {
    var _this = this;

    _this['attributes'] = attributes;


  };

  /**
   * Constructs a <code>Block</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Block} obj Optional instance to populate.
   * @return {module:model/Block} The populated <code>Block</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('attributes')) {
        obj['attributes'] = ApiClient.convertToType(data['attributes'], [Attribute]);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('resourceKey')) {
        obj['resourceKey'] = ApiClient.convertToType(data['resourceKey'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Attribute>} attributes
   */
  exports.prototype['attributes'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} resourceKey
   */
  exports.prototype['resourceKey'] = undefined;



  return exports;
}));


