/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.CallService = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CallService model module.
   * @module model/CallService
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>CallService</code>.
   * Representation of a call service
   * @alias module:model/CallService
   * @class
   * @param serviceId {Number} the Id of the CallService
   */
  var exports = function(serviceId) {
    var _this = this;


    _this['serviceId'] = serviceId;

  };

  /**
   * Constructs a <code>CallService</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CallService} obj Optional instance to populate.
   * @return {module:model/CallService} The populated <code>CallService</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
      if (data.hasOwnProperty('serviceId')) {
        obj['serviceId'] = ApiClient.convertToType(data['serviceId'], 'Number');
      }
      if (data.hasOwnProperty('serviceName')) {
        obj['serviceName'] = ApiClient.convertToType(data['serviceName'], 'String');
      }
    }
    return obj;
  }

  /**
   * the label of the CallService that is used in the UI
   * @member {String} label
   */
  exports.prototype['label'] = undefined;
  /**
   * the Id of the CallService
   * @member {Number} serviceId
   */
  exports.prototype['serviceId'] = undefined;
  /**
   * the name of the CallService
   * @member {String} serviceName
   */
  exports.prototype['serviceName'] = undefined;



  return exports;
}));


