/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.ConferenceConfigurationTexts = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ConferenceConfigurationTexts model module.
   * @module model/ConferenceConfigurationTexts
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>ConferenceConfigurationTexts</code>.
   * A representation of STARFACE managed configuration email subject and email body
   * @alias module:model/ConferenceConfigurationTexts
   * @class
   * @param eMailBody {String} 
   * @param eMailSubject {String} 
   */
  var exports = function(eMailBody, eMailSubject) {
    var _this = this;

    _this['eMailBody'] = eMailBody;
    _this['eMailSubject'] = eMailSubject;
  };

  /**
   * Constructs a <code>ConferenceConfigurationTexts</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConferenceConfigurationTexts} obj Optional instance to populate.
   * @return {module:model/ConferenceConfigurationTexts} The populated <code>ConferenceConfigurationTexts</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('eMailBody')) {
        obj['eMailBody'] = ApiClient.convertToType(data['eMailBody'], 'String');
      }
      if (data.hasOwnProperty('eMailSubject')) {
        obj['eMailSubject'] = ApiClient.convertToType(data['eMailSubject'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} eMailBody
   */
  exports.prototype['eMailBody'] = undefined;
  /**
   * @member {String} eMailSubject
   */
  exports.prototype['eMailSubject'] = undefined;



  return exports;
}));


