/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Block', 'model/ContactSummary', 'model/RequestMetadata'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Block'), require('./ContactSummary'), require('./RequestMetadata'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.ContactList = factory(root.StarfaceRestApi.ApiClient, root.StarfaceRestApi.Block, root.StarfaceRestApi.ContactSummary, root.StarfaceRestApi.RequestMetadata);
  }
}(this, function(ApiClient, Block, ContactSummary, RequestMetadata) {
  'use strict';




  /**
   * The ContactList model module.
   * @module model/ContactList
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>ContactList</code>.
   * Bandwidth-saving return object for lists of contacts. It returns the contact schema for the summary block and the phone numbers block. The ContactSummary data can be interpreted using the contact scheme.
   * @alias module:model/ContactList
   * @class
   * @param contacts {Array.<module:model/ContactSummary>} 
   */
  var exports = function(contacts) {
    var _this = this;

    _this['contacts'] = contacts;



  };

  /**
   * Constructs a <code>ContactList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContactList} obj Optional instance to populate.
   * @return {module:model/ContactList} The populated <code>ContactList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('contacts')) {
        obj['contacts'] = ApiClient.convertToType(data['contacts'], [ContactSummary]);
      }
      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = RequestMetadata.constructFromObject(data['metadata']);
      }
      if (data.hasOwnProperty('phoneNumbersBlockSchema')) {
        obj['phoneNumbersBlockSchema'] = Block.constructFromObject(data['phoneNumbersBlockSchema']);
      }
      if (data.hasOwnProperty('summaryBlockSchema')) {
        obj['summaryBlockSchema'] = Block.constructFromObject(data['summaryBlockSchema']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ContactSummary>} contacts
   */
  exports.prototype['contacts'] = undefined;
  /**
   * @member {module:model/RequestMetadata} metadata
   */
  exports.prototype['metadata'] = undefined;
  /**
   * @member {module:model/Block} phoneNumbersBlockSchema
   */
  exports.prototype['phoneNumbersBlockSchema'] = undefined;
  /**
   * @member {module:model/Block} summaryBlockSchema
   */
  exports.prototype['summaryBlockSchema'] = undefined;



  return exports;
}));


