/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.EditFunctionKeyCallList = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EditFunctionKeyCallList model module.
   * @module model/EditFunctionKeyCallList
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>EditFunctionKeyCallList</code>.
   * A representation of a EditFunctionKeyCallList Form
   * @alias module:model/EditFunctionKeyCallList
   * @class
   * @param callListRequest {module:model/EditFunctionKeyCallList.CallListRequestEnum} the call list type of the FunctionKey
   * @param callListRequests {Array.<String>} list of possible callListRequests
   * @param name {String} the name of the FunctionKey
   */
  var exports = function(callListRequest, callListRequests, name) {
    var _this = this;

    _this['callListRequest'] = callListRequest;
    _this['callListRequests'] = callListRequests;
    _this['name'] = name;
  };

  /**
   * Constructs a <code>EditFunctionKeyCallList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EditFunctionKeyCallList} obj Optional instance to populate.
   * @return {module:model/EditFunctionKeyCallList} The populated <code>EditFunctionKeyCallList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('callListRequest')) {
        obj['callListRequest'] = ApiClient.convertToType(data['callListRequest'], 'String');
      }
      if (data.hasOwnProperty('callListRequests')) {
        obj['callListRequests'] = ApiClient.convertToType(data['callListRequests'], ['String']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * the call list type of the FunctionKey
   * @member {module:model/EditFunctionKeyCallList.CallListRequestEnum} callListRequest
   */
  exports.prototype['callListRequest'] = undefined;
  /**
   * list of possible callListRequests
   * @member {Array.<String>} callListRequests
   */
  exports.prototype['callListRequests'] = undefined;
  /**
   * the name of the FunctionKey
   * @member {String} name
   */
  exports.prototype['name'] = undefined;


  /**
   * Allowed values for the <code>callListRequest</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CallListRequestEnum = {
    /**
     * value: "INCOMING"
     * @const
     */
    "INCOMING": "INCOMING",
    /**
     * value: "OUTGOING"
     * @const
     */
    "OUTGOING": "OUTGOING",
    /**
     * value: "MISSED"
     * @const
     */
    "MISSED": "MISSED"  };


  return exports;
}));


