/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Account'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Account'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.EditFunctionKeyBusyLampField = factory(root.StarfaceRestApi.ApiClient, root.StarfaceRestApi.Account);
  }
}(this, function(ApiClient, Account) {
  'use strict';




  /**
   * The EditFunctionKeyBusyLampField model module.
   * @module model/EditFunctionKeyBusyLampField
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>EditFunctionKeyBusyLampField</code>.
   * A representation of a EditFunctionKeyBusyLampField Form
   * @alias module:model/EditFunctionKeyBusyLampField
   * @class
   * @param blfAccountId {Number} accountId of busy lamp field
   * @param blfDisplayInformation {String} the display information of the blf accountid
   * @param name {String} the name of the FunctionKey
   * @param _number {String} the user telephonenumber of the FunctionKey
   */
  var exports = function(blfAccountId, blfDisplayInformation, name, _number) {
    var _this = this;


    _this['blfAccountId'] = blfAccountId;
    _this['blfDisplayInformation'] = blfDisplayInformation;
    _this['name'] = name;
    _this['number'] = _number;
  };

  /**
   * Constructs a <code>EditFunctionKeyBusyLampField</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EditFunctionKeyBusyLampField} obj Optional instance to populate.
   * @return {module:model/EditFunctionKeyBusyLampField} The populated <code>EditFunctionKeyBusyLampField</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('availableAccounts')) {
        obj['availableAccounts'] = ApiClient.convertToType(data['availableAccounts'], [Account]);
      }
      if (data.hasOwnProperty('blfAccountId')) {
        obj['blfAccountId'] = ApiClient.convertToType(data['blfAccountId'], 'Number');
      }
      if (data.hasOwnProperty('blfDisplayInformation')) {
        obj['blfDisplayInformation'] = ApiClient.convertToType(data['blfDisplayInformation'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('number')) {
        obj['number'] = ApiClient.convertToType(data['number'], 'String');
      }
    }
    return obj;
  }

  /**
   * the available accounts of the FunctionKey
   * @member {Array.<module:model/Account>} availableAccounts
   */
  exports.prototype['availableAccounts'] = undefined;
  /**
   * accountId of busy lamp field
   * @member {Number} blfAccountId
   */
  exports.prototype['blfAccountId'] = undefined;
  /**
   * the display information of the blf accountid
   * @member {String} blfDisplayInformation
   */
  exports.prototype['blfDisplayInformation'] = undefined;
  /**
   * the name of the FunctionKey
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * the user telephonenumber of the FunctionKey
   * @member {String} number
   */
  exports.prototype['number'] = undefined;



  return exports;
}));


