/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PhoneNumber'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PhoneNumber'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.EditFunctionKeySignalNumber = factory(root.StarfaceRestApi.ApiClient, root.StarfaceRestApi.PhoneNumber);
  }
}(this, function(ApiClient, PhoneNumber) {
  'use strict';




  /**
   * The EditFunctionKeySignalNumber model module.
   * @module model/EditFunctionKeySignalNumber
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>EditFunctionKeySignalNumber</code>.
   * A representation of a EditFunctionKeySignalNumber Form
   * @alias module:model/EditFunctionKeySignalNumber
   * @class
   * @param name {String} the name of the FunctionKey
   * @param phoneNumber {String} the phoneNumber of the FunctionKey
   * @param phoneNumberId {Number} the phoneNumberId of the FunctionKey
   * @param possibleSignalnumbers {Array.<module:model/PhoneNumber>} the possible signal phonenumbers
   */
  var exports = function(name, phoneNumber, phoneNumberId, possibleSignalnumbers) {
    var _this = this;

    _this['name'] = name;
    _this['phoneNumber'] = phoneNumber;
    _this['phoneNumberId'] = phoneNumberId;
    _this['possibleSignalnumbers'] = possibleSignalnumbers;
  };

  /**
   * Constructs a <code>EditFunctionKeySignalNumber</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EditFunctionKeySignalNumber} obj Optional instance to populate.
   * @return {module:model/EditFunctionKeySignalNumber} The populated <code>EditFunctionKeySignalNumber</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('phoneNumber')) {
        obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
      }
      if (data.hasOwnProperty('phoneNumberId')) {
        obj['phoneNumberId'] = ApiClient.convertToType(data['phoneNumberId'], 'Number');
      }
      if (data.hasOwnProperty('possibleSignalnumbers')) {
        obj['possibleSignalnumbers'] = ApiClient.convertToType(data['possibleSignalnumbers'], [PhoneNumber]);
      }
    }
    return obj;
  }

  /**
   * the name of the FunctionKey
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * the phoneNumber of the FunctionKey
   * @member {String} phoneNumber
   */
  exports.prototype['phoneNumber'] = undefined;
  /**
   * the phoneNumberId of the FunctionKey
   * @member {Number} phoneNumberId
   */
  exports.prototype['phoneNumberId'] = undefined;
  /**
   * the possible signal phonenumbers
   * @member {Array.<module:model/PhoneNumber>} possibleSignalnumbers
   */
  exports.prototype['possibleSignalnumbers'] = undefined;



  return exports;
}));


