/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.EditFunctionKeyForwardCall = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EditFunctionKeyForwardCall model module.
   * @module model/EditFunctionKeyForwardCall
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>EditFunctionKeyForwardCall</code>.
   * A representation of a EditFunctionKeyForwardCall Form
   * @alias module:model/EditFunctionKeyForwardCall
   * @class
   * @param forwardType {module:model/EditFunctionKeyForwardCall.ForwardTypeEnum} the forward type always busy timeout
   * @param forwardTypes {Array.<String>} the name of the FunctionKey
   * @param name {String} the name of the FunctionKey
   */
  var exports = function(forwardType, forwardTypes, name) {
    var _this = this;

    _this['forwardType'] = forwardType;
    _this['forwardTypes'] = forwardTypes;
    _this['name'] = name;
  };

  /**
   * Constructs a <code>EditFunctionKeyForwardCall</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EditFunctionKeyForwardCall} obj Optional instance to populate.
   * @return {module:model/EditFunctionKeyForwardCall} The populated <code>EditFunctionKeyForwardCall</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('forwardType')) {
        obj['forwardType'] = ApiClient.convertToType(data['forwardType'], 'String');
      }
      if (data.hasOwnProperty('forwardTypes')) {
        obj['forwardTypes'] = ApiClient.convertToType(data['forwardTypes'], ['String']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * the forward type always busy timeout
   * @member {module:model/EditFunctionKeyForwardCall.ForwardTypeEnum} forwardType
   */
  exports.prototype['forwardType'] = undefined;
  /**
   * the name of the FunctionKey
   * @member {Array.<String>} forwardTypes
   */
  exports.prototype['forwardTypes'] = undefined;
  /**
   * the name of the FunctionKey
   * @member {String} name
   */
  exports.prototype['name'] = undefined;


  /**
   * Allowed values for the <code>forwardType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ForwardTypeEnum = {
    /**
     * value: "ALWAYS"
     * @const
     */
    "ALWAYS": "ALWAYS",
    /**
     * value: "BUSY"
     * @const
     */
    "BUSY": "BUSY",
    /**
     * value: "TIMEOUT"
     * @const
     */
    "TIMEOUT": "TIMEOUT"  };


  return exports;
}));


