/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EditFunctionKeyForwardNumberUnconditionalNumberSetting'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EditFunctionKeyForwardNumberUnconditionalNumberSetting'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.EditFunctionKeyForwardNumberUnconditional = factory(root.StarfaceRestApi.ApiClient, root.StarfaceRestApi.EditFunctionKeyForwardNumberUnconditionalNumberSetting);
  }
}(this, function(ApiClient, EditFunctionKeyForwardNumberUnconditionalNumberSetting) {
  'use strict';




  /**
   * The EditFunctionKeyForwardNumberUnconditional model module.
   * @module model/EditFunctionKeyForwardNumberUnconditional
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>EditFunctionKeyForwardNumberUnconditional</code>.
   * A representation of a EditFunctionKeyForwardNumberUnconditional Form
   * @alias module:model/EditFunctionKeyForwardNumberUnconditional
   * @class
   * @param editFunctionKeyFnuNumberSetting {Array.<module:model/EditFunctionKeyForwardNumberUnconditionalNumberSetting>} 
   * @param name {String} the name of the FunctionKey
   */
  var exports = function(editFunctionKeyFnuNumberSetting, name) {
    var _this = this;

    _this['editFunctionKeyFnuNumberSetting'] = editFunctionKeyFnuNumberSetting;
    _this['name'] = name;
  };

  /**
   * Constructs a <code>EditFunctionKeyForwardNumberUnconditional</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EditFunctionKeyForwardNumberUnconditional} obj Optional instance to populate.
   * @return {module:model/EditFunctionKeyForwardNumberUnconditional} The populated <code>EditFunctionKeyForwardNumberUnconditional</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('editFunctionKeyFnuNumberSetting')) {
        obj['editFunctionKeyFnuNumberSetting'] = ApiClient.convertToType(data['editFunctionKeyFnuNumberSetting'], [EditFunctionKeyForwardNumberUnconditionalNumberSetting]);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/EditFunctionKeyForwardNumberUnconditionalNumberSetting>} editFunctionKeyFnuNumberSetting
   */
  exports.prototype['editFunctionKeyFnuNumberSetting'] = undefined;
  /**
   * the name of the FunctionKey
   * @member {String} name
   */
  exports.prototype['name'] = undefined;



  return exports;
}));


