/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.EditFunctionKeyParkAndOrbit = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EditFunctionKeyParkAndOrbit model module.
   * @module model/EditFunctionKeyParkAndOrbit
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>EditFunctionKeyParkAndOrbit</code>.
   * A representation of a EditFunctionKeyParkAndOrbit Form
   * @alias module:model/EditFunctionKeyParkAndOrbit
   * @class
   * @param name {String} the name of the FunctionKey
   * @param parkAndOrbitNumber {String} the parkAndOrbitNumber of the FunctionKey
   * @param parkAndOrbitNumbers {Array.<String>} the list of park and orbit numbers
   */
  var exports = function(name, parkAndOrbitNumber, parkAndOrbitNumbers) {
    var _this = this;

    _this['name'] = name;
    _this['parkAndOrbitNumber'] = parkAndOrbitNumber;
    _this['parkAndOrbitNumbers'] = parkAndOrbitNumbers;
  };

  /**
   * Constructs a <code>EditFunctionKeyParkAndOrbit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EditFunctionKeyParkAndOrbit} obj Optional instance to populate.
   * @return {module:model/EditFunctionKeyParkAndOrbit} The populated <code>EditFunctionKeyParkAndOrbit</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('parkAndOrbitNumber')) {
        obj['parkAndOrbitNumber'] = ApiClient.convertToType(data['parkAndOrbitNumber'], 'String');
      }
      if (data.hasOwnProperty('parkAndOrbitNumbers')) {
        obj['parkAndOrbitNumbers'] = ApiClient.convertToType(data['parkAndOrbitNumbers'], ['String']);
      }
    }
    return obj;
  }

  /**
   * the name of the FunctionKey
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * the parkAndOrbitNumber of the FunctionKey
   * @member {String} parkAndOrbitNumber
   */
  exports.prototype['parkAndOrbitNumber'] = undefined;
  /**
   * the list of park and orbit numbers
   * @member {Array.<String>} parkAndOrbitNumbers
   */
  exports.prototype['parkAndOrbitNumbers'] = undefined;



  return exports;
}));


