/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.EditFunctionKeyGroupLoginGroupSettings = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EditFunctionKeyGroupLoginGroupSettings model module.
   * @module model/EditFunctionKeyGroupLoginGroupSettings
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>EditFunctionKeyGroupLoginGroupSettings</code>.
   * A representation of a EditFunctionKeyGroupLoginGroupSettings Form
   * @alias module:model/EditFunctionKeyGroupLoginGroupSettings
   * @class
   * @param activated {Boolean} is number setting activated
   * @param groupId {Number} the groupId
   * @param groupname {String} the groupname
   */
  var exports = function(activated, groupId, groupname) {
    var _this = this;

    _this['activated'] = activated;
    _this['groupId'] = groupId;
    _this['groupname'] = groupname;
  };

  /**
   * Constructs a <code>EditFunctionKeyGroupLoginGroupSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EditFunctionKeyGroupLoginGroupSettings} obj Optional instance to populate.
   * @return {module:model/EditFunctionKeyGroupLoginGroupSettings} The populated <code>EditFunctionKeyGroupLoginGroupSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('activated')) {
        obj['activated'] = ApiClient.convertToType(data['activated'], 'Boolean');
      }
      if (data.hasOwnProperty('groupId')) {
        obj['groupId'] = ApiClient.convertToType(data['groupId'], 'Number');
      }
      if (data.hasOwnProperty('groupname')) {
        obj['groupname'] = ApiClient.convertToType(data['groupname'], 'String');
      }
    }
    return obj;
  }

  /**
   * is number setting activated
   * @member {Boolean} activated
   */
  exports.prototype['activated'] = undefined;
  /**
   * the groupId
   * @member {Number} groupId
   */
  exports.prototype['groupId'] = undefined;
  /**
   * the groupname
   * @member {String} groupname
   */
  exports.prototype['groupname'] = undefined;



  return exports;
}));


