/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.FunctionKey = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FunctionKey model module.
   * @module model/FunctionKey
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>FunctionKey</code>.
   * A representation of a FunctionKey
   * @alias module:model/FunctionKey
   * @class
   * @param accountId {String} the accountId of the FunctionKey
   * @param functionKeyType {module:model/FunctionKey.FunctionKeyTypeEnum} The type of the FunctionKey determining the concrete FunctionKey implementation
   * @param id {String} the Id of the FunctionKey
   * @param name {String} the display name of the FunctionKey
   * @param position {Number} the position of the FunctionKey wthin its FunctionKeySet
   */
  var exports = function(accountId, functionKeyType, id, name, position) {
    var _this = this;

    _this['accountId'] = accountId;









    _this['functionKeyType'] = functionKeyType;


    _this['id'] = id;
    _this['name'] = name;

    _this['position'] = position;

  };

  /**
   * Constructs a <code>FunctionKey</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FunctionKey} obj Optional instance to populate.
   * @return {module:model/FunctionKey} The populated <code>FunctionKey</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accountId')) {
        obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
      }
      if (data.hasOwnProperty('activateModuleIds')) {
        obj['activateModuleIds'] = ApiClient.convertToType(data['activateModuleIds'], ['String']);
      }
      if (data.hasOwnProperty('addressBookFolderName')) {
        obj['addressBookFolderName'] = ApiClient.convertToType(data['addressBookFolderName'], 'String');
      }
      if (data.hasOwnProperty('addressbookRequest')) {
        obj['addressbookRequest'] = ApiClient.convertToType(data['addressbookRequest'], 'String');
      }
      if (data.hasOwnProperty('blfAccountId')) {
        obj['blfAccountId'] = ApiClient.convertToType(data['blfAccountId'], 'Number');
      }
      if (data.hasOwnProperty('callListRequest')) {
        obj['callListRequest'] = ApiClient.convertToType(data['callListRequest'], 'String');
      }
      if (data.hasOwnProperty('directCallTargetnumber')) {
        obj['directCallTargetnumber'] = ApiClient.convertToType(data['directCallTargetnumber'], 'String');
      }
      if (data.hasOwnProperty('displayNumberId')) {
        obj['displayNumberId'] = ApiClient.convertToType(data['displayNumberId'], 'Number');
      }
      if (data.hasOwnProperty('dtmf')) {
        obj['dtmf'] = ApiClient.convertToType(data['dtmf'], 'String');
      }
      if (data.hasOwnProperty('forwardType')) {
        obj['forwardType'] = ApiClient.convertToType(data['forwardType'], 'String');
      }
      if (data.hasOwnProperty('functionKeyType')) {
        obj['functionKeyType'] = ApiClient.convertToType(data['functionKeyType'], 'String');
      }
      if (data.hasOwnProperty('genericURL')) {
        obj['genericURL'] = ApiClient.convertToType(data['genericURL'], 'String');
      }
      if (data.hasOwnProperty('groupIds')) {
        obj['groupIds'] = ApiClient.convertToType(data['groupIds'], ['Number']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('poNumber')) {
        obj['poNumber'] = ApiClient.convertToType(data['poNumber'], 'String');
      }
      if (data.hasOwnProperty('position')) {
        obj['position'] = ApiClient.convertToType(data['position'], 'Number');
      }
      if (data.hasOwnProperty('redirectNumberIds')) {
        obj['redirectNumberIds'] = ApiClient.convertToType(data['redirectNumberIds'], ['Number']);
      }
    }
    return obj;
  }

  /**
   * the accountId of the FunctionKey
   * @member {String} accountId
   */
  exports.prototype['accountId'] = undefined;
  /**
   * Modules to activate
   * @member {Array.<String>} activateModuleIds
   */
  exports.prototype['activateModuleIds'] = undefined;
  /**
   * AddressBookFolderName
   * @member {String} addressBookFolderName
   */
  exports.prototype['addressBookFolderName'] = undefined;
  /**
   * Type of AddressbookRequest
   * @member {module:model/FunctionKey.AddressbookRequestEnum} addressbookRequest
   */
  exports.prototype['addressbookRequest'] = undefined;
  /**
   * AccountId of busy lamp field
   * @member {Number} blfAccountId
   */
  exports.prototype['blfAccountId'] = undefined;
  /**
   * Type of requested list
   * @member {module:model/FunctionKey.CallListRequestEnum} callListRequest
   */
  exports.prototype['callListRequest'] = undefined;
  /**
   * Number to call
   * @member {String} directCallTargetnumber
   */
  exports.prototype['directCallTargetnumber'] = undefined;
  /**
   * Displaynumberid to signal
   * @member {Number} displayNumberId
   */
  exports.prototype['displayNumberId'] = undefined;
  /**
   * Dtmf to send
   * @member {String} dtmf
   */
  exports.prototype['dtmf'] = undefined;
  /**
   * Type of forward
   * @member {module:model/FunctionKey.ForwardTypeEnum} forwardType
   */
  exports.prototype['forwardType'] = undefined;
  /**
   * The type of the FunctionKey determining the concrete FunctionKey implementation
   * @member {module:model/FunctionKey.FunctionKeyTypeEnum} functionKeyType
   */
  exports.prototype['functionKeyType'] = undefined;
  /**
   * generic URL to send
   * @member {String} genericURL
   */
  exports.prototype['genericURL'] = undefined;
  /**
   * Groupids to activate or deactivate
   * @member {Array.<Number>} groupIds
   */
  exports.prototype['groupIds'] = undefined;
  /**
   * the Id of the FunctionKey
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * the display name of the FunctionKey
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Number of park and orbit position
   * @member {String} poNumber
   */
  exports.prototype['poNumber'] = undefined;
  /**
   * the position of the FunctionKey wthin its FunctionKeySet
   * @member {Number} position
   */
  exports.prototype['position'] = undefined;
  /**
   * NumberIds to redirect
   * @member {Array.<Number>} redirectNumberIds
   */
  exports.prototype['redirectNumberIds'] = undefined;


  /**
   * Allowed values for the <code>addressbookRequest</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AddressbookRequestEnum = {
    /**
     * value: "CONTACTLIST"
     * @const
     */
    "CONTACTLIST": "CONTACTLIST",
    /**
     * value: "CONTACTSEARCH"
     * @const
     */
    "CONTACTSEARCH": "CONTACTSEARCH"  };

  /**
   * Allowed values for the <code>callListRequest</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CallListRequestEnum = {
    /**
     * value: "INCOMING"
     * @const
     */
    "INCOMING": "INCOMING",
    /**
     * value: "OUTGOING"
     * @const
     */
    "OUTGOING": "OUTGOING",
    /**
     * value: "MISSED"
     * @const
     */
    "MISSED": "MISSED"  };

  /**
   * Allowed values for the <code>forwardType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ForwardTypeEnum = {
    /**
     * value: "ALWAYS"
     * @const
     */
    "ALWAYS": "ALWAYS",
    /**
     * value: "BUSY"
     * @const
     */
    "BUSY": "BUSY",
    /**
     * value: "TIMEOUT"
     * @const
     */
    "TIMEOUT": "TIMEOUT"  };

  /**
   * Allowed values for the <code>functionKeyType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.FunctionKeyTypeEnum = {
    /**
     * value: "SIGNALNUMBER"
     * @const
     */
    "SIGNALNUMBER": "SIGNALNUMBER",
    /**
     * value: "SEPARATOR"
     * @const
     */
    "SEPARATOR": "SEPARATOR",
    /**
     * value: "QUICKDIAL"
     * @const
     */
    "QUICKDIAL": "QUICKDIAL",
    /**
     * value: "PHONEGENERICURL"
     * @const
     */
    "PHONEGENERICURL": "PHONEGENERICURL",
    /**
     * value: "PHONEDTMF"
     * @const
     */
    "PHONEDTMF": "PHONEDTMF",
    /**
     * value: "ADDRESSBOOK"
     * @const
     */
    "ADDRESSBOOK": "ADDRESSBOOK",
    /**
     * value: "PHONECALLLIST"
     * @const
     */
    "PHONECALLLIST": "PHONECALLLIST",
    /**
     * value: "PARKANDORBIT"
     * @const
     */
    "PARKANDORBIT": "PARKANDORBIT",
    /**
     * value: "MODULEACTIVATION"
     * @const
     */
    "MODULEACTIVATION": "MODULEACTIVATION",
    /**
     * value: "GROUPLOGIN"
     * @const
     */
    "GROUPLOGIN": "GROUPLOGIN",
    /**
     * value: "FORWARDNUMBER"
     * @const
     */
    "FORWARDNUMBER": "FORWARDNUMBER",
    /**
     * value: "FORWARD"
     * @const
     */
    "FORWARD": "FORWARD",
    /**
     * value: "DONOTDISTURB"
     * @const
     */
    "DONOTDISTURB": "DONOTDISTURB",
    /**
     * value: "COMPLETIONOFCALLSTOBUSYSUBSCRIBER"
     * @const
     */
    "COMPLETIONOFCALLSTOBUSYSUBSCRIBER": "COMPLETIONOFCALLSTOBUSYSUBSCRIBER",
    /**
     * value: "BUSYLAMPFIELD"
     * @const
     */
    "BUSYLAMPFIELD": "BUSYLAMPFIELD"  };


  return exports;
}));


