/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.FunctionKeySet = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FunctionKeySet model module.
   * @module model/FunctionKeySet
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>FunctionKeySet</code>.
   * An ordered set of FunctionKeys that can be used for changing the order of FunctionKeys
   * @alias module:model/FunctionKeySet
   * @class
   * @param id {String} the Id of the FunctionKeySet
   * @param keyOrder {Array.<String>} List of Ids of contained FunctionKeys. The ordering of this List defines the positioning of the FunctionKeys.
   * @param name {String} the name of the FunctionKeySet
   */
  var exports = function(id, keyOrder, name) {
    var _this = this;

    _this['id'] = id;
    _this['keyOrder'] = keyOrder;
    _this['name'] = name;
  };

  /**
   * Constructs a <code>FunctionKeySet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FunctionKeySet} obj Optional instance to populate.
   * @return {module:model/FunctionKeySet} The populated <code>FunctionKeySet</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('keyOrder')) {
        obj['keyOrder'] = ApiClient.convertToType(data['keyOrder'], ['String']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * the Id of the FunctionKeySet
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * List of Ids of contained FunctionKeys. The ordering of this List defines the positioning of the FunctionKeys.
   * @member {Array.<String>} keyOrder
   */
  exports.prototype['keyOrder'] = undefined;
  /**
   * the name of the FunctionKeySet
   * @member {String} name
   */
  exports.prototype['name'] = undefined;



  return exports;
}));


