/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.ManagedConferenceSummary = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ManagedConferenceSummary model module.
   * @module model/ManagedConferenceSummary
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>ManagedConferenceSummary</code>.
   * A representation of STARFACE managed conference summary
   * @alias module:model/ManagedConferenceSummary
   * @class
   * @param conferenceId {Number} 
   * @param isActive {Boolean} 
   * @param isReadonly {Boolean} 
   * @param isTerminated {Boolean} 
   * @param name {String} 
   * @param startTime {Number} 
   */
  var exports = function(conferenceId, isActive, isReadonly, isTerminated, name, startTime) {
    var _this = this;

    _this['conferenceId'] = conferenceId;
    _this['isActive'] = isActive;
    _this['isReadonly'] = isReadonly;
    _this['isTerminated'] = isTerminated;
    _this['name'] = name;
    _this['startTime'] = startTime;
  };

  /**
   * Constructs a <code>ManagedConferenceSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ManagedConferenceSummary} obj Optional instance to populate.
   * @return {module:model/ManagedConferenceSummary} The populated <code>ManagedConferenceSummary</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('conferenceId')) {
        obj['conferenceId'] = ApiClient.convertToType(data['conferenceId'], 'Number');
      }
      if (data.hasOwnProperty('isActive')) {
        obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
      }
      if (data.hasOwnProperty('isReadonly')) {
        obj['isReadonly'] = ApiClient.convertToType(data['isReadonly'], 'Boolean');
      }
      if (data.hasOwnProperty('isTerminated')) {
        obj['isTerminated'] = ApiClient.convertToType(data['isTerminated'], 'Boolean');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('startTime')) {
        obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} conferenceId
   */
  exports.prototype['conferenceId'] = undefined;
  /**
   * @member {Boolean} isActive
   */
  exports.prototype['isActive'] = undefined;
  /**
   * @member {Boolean} isReadonly
   */
  exports.prototype['isReadonly'] = undefined;
  /**
   * @member {Boolean} isTerminated
   */
  exports.prototype['isTerminated'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} startTime
   */
  exports.prototype['startTime'] = undefined;



  return exports;
}));


