/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.PhoneNumberAssignment = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PhoneNumberAssignment model module.
   * @module model/PhoneNumberAssignment
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>PhoneNumberAssignment</code>.
   * Representation of an assignment of a PhoneNumber to a User
   * @alias module:model/PhoneNumberAssignment
   * @class
   * @param accountId {Number} the Id of the Account
   * @param phoneNumberId {Number} the Id of the PhoneNumber that is assigned to the User
   * @param serviceId {Number} the Id of the call service rule that is used for this phone number.
   */
  var exports = function(accountId, phoneNumberId, serviceId) {
    var _this = this;

    _this['accountId'] = accountId;
    _this['phoneNumberId'] = phoneNumberId;
    _this['serviceId'] = serviceId;
  };

  /**
   * Constructs a <code>PhoneNumberAssignment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PhoneNumberAssignment} obj Optional instance to populate.
   * @return {module:model/PhoneNumberAssignment} The populated <code>PhoneNumberAssignment</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accountId')) {
        obj['accountId'] = ApiClient.convertToType(data['accountId'], 'Number');
      }
      if (data.hasOwnProperty('phoneNumberId')) {
        obj['phoneNumberId'] = ApiClient.convertToType(data['phoneNumberId'], 'Number');
      }
      if (data.hasOwnProperty('serviceId')) {
        obj['serviceId'] = ApiClient.convertToType(data['serviceId'], 'Number');
      }
    }
    return obj;
  }

  /**
   * the Id of the Account
   * @member {Number} accountId
   */
  exports.prototype['accountId'] = undefined;
  /**
   * the Id of the PhoneNumber that is assigned to the User
   * @member {Number} phoneNumberId
   */
  exports.prototype['phoneNumberId'] = undefined;
  /**
   * the Id of the call service rule that is used for this phone number.
   * @member {Number} serviceId
   */
  exports.prototype['serviceId'] = undefined;



  return exports;
}));


