/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.RedirectPhoneNumberDestination = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RedirectPhoneNumberDestination model module.
   * @module model/RedirectPhoneNumberDestination
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>RedirectPhoneNumberDestination</code>.
   * This RedirectDestination will redirect to a phoneNumber
   * @alias module:model/RedirectPhoneNumberDestination
   * @class
   * @param phoneNumber {String} 
   * @param redirectDestinationType {module:model/RedirectPhoneNumberDestination.RedirectDestinationTypeEnum} The type of the RedirectDestination determining the concrete RedirectDestination implementation
   */
  var exports = function(phoneNumber, redirectDestinationType) {
    var _this = this;

    _this['phoneNumber'] = phoneNumber;
    _this['redirectDestinationType'] = redirectDestinationType;
  };

  /**
   * Constructs a <code>RedirectPhoneNumberDestination</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RedirectPhoneNumberDestination} obj Optional instance to populate.
   * @return {module:model/RedirectPhoneNumberDestination} The populated <code>RedirectPhoneNumberDestination</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('phoneNumber')) {
        obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
      }
      if (data.hasOwnProperty('redirectDestinationType')) {
        obj['redirectDestinationType'] = ApiClient.convertToType(data['redirectDestinationType'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} phoneNumber
   */
  exports.prototype['phoneNumber'] = undefined;
  /**
   * The type of the RedirectDestination determining the concrete RedirectDestination implementation
   * @member {module:model/RedirectPhoneNumberDestination.RedirectDestinationTypeEnum} redirectDestinationType
   */
  exports.prototype['redirectDestinationType'] = undefined;


  /**
   * Allowed values for the <code>redirectDestinationType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RedirectDestinationTypeEnum = {
    /**
     * value: "MAILBOX"
     * @const
     */
    "MAILBOX": "MAILBOX",
    /**
     * value: "PHONENUMBER"
     * @const
     */
    "PHONENUMBER": "PHONENUMBER"  };


  return exports;
}));


