/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.VoicemailboxListItem = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The VoicemailboxListItem model module.
   * @module model/VoicemailboxListItem
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>VoicemailboxListItem</code>.
   * A representation of a STARFACE voicemailbox list item
   * @alias module:model/VoicemailboxListItem
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>VoicemailboxListItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VoicemailboxListItem} obj Optional instance to populate.
   * @return {module:model/VoicemailboxListItem} The populated <code>VoicemailboxListItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('assignedgroups')) {
        obj['assignedgroups'] = ApiClient.convertToType(data['assignedgroups'], ['String']);
      }
      if (data.hasOwnProperty('assignedusers')) {
        obj['assignedusers'] = ApiClient.convertToType(data['assignedusers'], ['String']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('mailboxnumber')) {
        obj['mailboxnumber'] = ApiClient.convertToType(data['mailboxnumber'], 'String');
      }
      if (data.hasOwnProperty('voiceboxname')) {
        obj['voiceboxname'] = ApiClient.convertToType(data['voiceboxname'], 'String');
      }
    }
    return obj;
  }

  /**
   * the assigned groups of the voicemailbox
   * @member {Array.<String>} assignedgroups
   */
  exports.prototype['assignedgroups'] = undefined;
  /**
   * the assigned users of the voicemailbox
   * @member {Array.<String>} assignedusers
   */
  exports.prototype['assignedusers'] = undefined;
  /**
   * the id of the voicemailbox
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * the number of the voicemailbox
   * @member {String} mailboxnumber
   */
  exports.prototype['mailboxnumber'] = undefined;
  /**
   * the name of the voicemailbox
   * @member {String} voiceboxname
   */
  exports.prototype['voiceboxname'] = undefined;



  return exports;
}));


