/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StarfaceRestApi) {
      root.StarfaceRestApi = {};
    }
    root.StarfaceRestApi.VoicemailGroup = factory(root.StarfaceRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The VoicemailGroup model module.
   * @module model/VoicemailGroup
   * @version 6.7.0.22
   */

  /**
   * Constructs a new <code>VoicemailGroup</code>.
   * A representation of a STARFACE voicemailbox group
   * @alias module:model/VoicemailGroup
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>VoicemailGroup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VoicemailGroup} obj Optional instance to populate.
   * @return {module:model/VoicemailGroup} The populated <code>VoicemailGroup</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accountId')) {
        obj['accountId'] = ApiClient.convertToType(data['accountId'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('sendMail')) {
        obj['sendMail'] = ApiClient.convertToType(data['sendMail'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * the account id of the voicemailbox group
   * @member {Number} accountId
   */
  exports.prototype['accountId'] = undefined;
  /**
   * the name of the voicemailbox group
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * the send mail option of the voicemailbox group
   * @member {Boolean} sendMail
   */
  exports.prototype['sendMail'] = undefined;



  return exports;
}));


