/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarfaceRestApi);
  }
}(this, function(expect, StarfaceRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarfaceRestApi.ConferencesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConferencesApi', function() {
    describe('deleteManagedConference', function() {
      it('should call deleteManagedConference successfully', function(done) {
        //uncomment below and update the code to test deleteManagedConference
        //instance.deleteManagedConference(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getConferenceConfiguration', function() {
      it('should call getConferenceConfiguration successfully', function(done) {
        //uncomment below and update the code to test getConferenceConfiguration
        //instance.getConferenceConfiguration(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDefaultTexts', function() {
      it('should call getDefaultTexts successfully', function(done) {
        //uncomment below and update the code to test getDefaultTexts
        //instance.getDefaultTexts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getManagedConference', function() {
      it('should call getManagedConference successfully', function(done) {
        //uncomment below and update the code to test getManagedConference
        //instance.getManagedConference(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getManagedConferenceList', function() {
      it('should call getManagedConferenceList successfully', function(done) {
        //uncomment below and update the code to test getManagedConferenceList
        //instance.getManagedConferenceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postManagedConference', function() {
      it('should call postManagedConference successfully', function(done) {
        //uncomment below and update the code to test postManagedConference
        //instance.postManagedConference(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putConferenceConfiguration', function() {
      it('should call putConferenceConfiguration successfully', function(done) {
        //uncomment below and update the code to test putConferenceConfiguration
        //instance.putConferenceConfiguration(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putManagedConference', function() {
      it('should call putManagedConference successfully', function(done) {
        //uncomment below and update the code to test putManagedConference
        //instance.putManagedConference(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('startManagedConference', function() {
      it('should call startManagedConference successfully', function(done) {
        //uncomment below and update the code to test startManagedConference
        //instance.startManagedConference(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
