/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarfaceRestApi);
  }
}(this, function(expect, StarfaceRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarfaceRestApi.PhoneNumbersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PhoneNumbersApi', function() {
    describe('assignPhoneNumber', function() {
      it('should call assignPhoneNumber successfully', function(done) {
        //uncomment below and update the code to test assignPhoneNumber
        //instance.assignPhoneNumber(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePhoneNumberAssignment', function() {
      it('should call deletePhoneNumberAssignment successfully', function(done) {
        //uncomment below and update the code to test deletePhoneNumberAssignment
        //instance.deletePhoneNumberAssignment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePhoneNumberAssignments', function() {
      it('should call deletePhoneNumberAssignments successfully', function(done) {
        //uncomment below and update the code to test deletePhoneNumberAssignments
        //instance.deletePhoneNumberAssignments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNumbersForAssignedPhone', function() {
      it('should call getNumbersForAssignedPhone successfully', function(done) {
        //uncomment below and update the code to test getNumbersForAssignedPhone
        //instance.getNumbersForAssignedPhone(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhoneNumber', function() {
      it('should call getPhoneNumber successfully', function(done) {
        //uncomment below and update the code to test getPhoneNumber
        //instance.getPhoneNumber(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhoneNumberAssignment', function() {
      it('should call getPhoneNumberAssignment successfully', function(done) {
        //uncomment below and update the code to test getPhoneNumberAssignment
        //instance.getPhoneNumberAssignment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhoneNumberConfig', function() {
      it('should call getPhoneNumberConfig successfully', function(done) {
        //uncomment below and update the code to test getPhoneNumberConfig
        //instance.getPhoneNumberConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhoneNumbers', function() {
      it('should call getPhoneNumbers successfully', function(done) {
        //uncomment below and update the code to test getPhoneNumbers
        //instance.getPhoneNumbers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listPhoneNumberAssignment', function() {
      it('should call listPhoneNumberAssignment successfully', function(done) {
        //uncomment below and update the code to test listPhoneNumberAssignment
        //instance.listPhoneNumberAssignment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putPhoneNumberConfig', function() {
      it('should call putPhoneNumberConfig successfully', function(done) {
        //uncomment below and update the code to test putPhoneNumberConfig
        //instance.putPhoneNumberConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateNumbersForAssignedPhones', function() {
      it('should call updateNumbersForAssignedPhones successfully', function(done) {
        //uncomment below and update the code to test updateNumbersForAssignedPhones
        //instance.updateNumbersForAssignedPhones(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePhoneNumberAssignments', function() {
      it('should call updatePhoneNumberAssignments successfully', function(done) {
        //uncomment below and update the code to test updatePhoneNumberAssignments
        //instance.updatePhoneNumberAssignments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
