/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarfaceRestApi);
  }
}(this, function(expect, StarfaceRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarfaceRestApi.Account();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Account', function() {
    it('should create an instance of Account', function() {
      // uncomment below and update the code to test Account
      //var instance = new StarfaceRestApi.Account();
      //expect(instance).to.be.a(StarfaceRestApi.Account);
    });

    it('should have the property accountId (base name: "accountId")', function() {
      // uncomment below and update the code to test the property accountId
      //var instance = new StarfaceRestApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property displayInformation (base name: "displayInformation")', function() {
      // uncomment below and update the code to test the property displayInformation
      //var instance = new StarfaceRestApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property federationname (base name: "federationname")', function() {
      // uncomment below and update the code to test the property federationname
      //var instance = new StarfaceRestApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property firstname (base name: "firstname")', function() {
      // uncomment below and update the code to test the property firstname
      //var instance = new StarfaceRestApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property lastname (base name: "lastname")', function() {
      // uncomment below and update the code to test the property lastname
      //var instance = new StarfaceRestApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property local (base name: "local")', function() {
      // uncomment below and update the code to test the property local
      //var instance = new StarfaceRestApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property primaryInternalPhoneNumber (base name: "primaryInternalPhoneNumber")', function() {
      // uncomment below and update the code to test the property primaryInternalPhoneNumber
      //var instance = new StarfaceRestApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new StarfaceRestApi.Account();
      //expect(instance).to.be();
    });

  });

}));
