/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarfaceRestApi);
  }
}(this, function(expect, StarfaceRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarfaceRestApi.ConferenceConfiguration();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConferenceConfiguration', function() {
    it('should create an instance of ConferenceConfiguration', function() {
      // uncomment below and update the code to test ConferenceConfiguration
      //var instance = new StarfaceRestApi.ConferenceConfiguration();
      //expect(instance).to.be.a(StarfaceRestApi.ConferenceConfiguration);
    });

    it('should have the property eMailBody (base name: "eMailBody")', function() {
      // uncomment below and update the code to test the property eMailBody
      //var instance = new StarfaceRestApi.ConferenceConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property eMailSubject (base name: "eMailSubject")', function() {
      // uncomment below and update the code to test the property eMailSubject
      //var instance = new StarfaceRestApi.ConferenceConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property externalNumberId (base name: "externalNumberId")', function() {
      // uncomment below and update the code to test the property externalNumberId
      //var instance = new StarfaceRestApi.ConferenceConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property internalNumberId (base name: "internalNumberId")', function() {
      // uncomment below and update the code to test the property internalNumberId
      //var instance = new StarfaceRestApi.ConferenceConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "language")', function() {
      // uncomment below and update the code to test the property language
      //var instance = new StarfaceRestApi.ConferenceConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property serverAddress (base name: "serverAddress")', function() {
      // uncomment below and update the code to test the property serverAddress
      //var instance = new StarfaceRestApi.ConferenceConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property variables (base name: "variables")', function() {
      // uncomment below and update the code to test the property variables
      //var instance = new StarfaceRestApi.ConferenceConfiguration();
      //expect(instance).to.be();
    });

  });

}));
