/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarfaceRestApi);
  }
}(this, function(expect, StarfaceRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarfaceRestApi.EditFunctionKey();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EditFunctionKey', function() {
    it('should create an instance of EditFunctionKey', function() {
      // uncomment below and update the code to test EditFunctionKey
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be.a(StarfaceRestApi.EditFunctionKey);
    });

    it('should have the property editFunctionKeyBusyLampField (base name: "editFunctionKeyBusyLampField")', function() {
      // uncomment below and update the code to test the property editFunctionKeyBusyLampField
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeyCallList (base name: "editFunctionKeyCallList")', function() {
      // uncomment below and update the code to test the property editFunctionKeyCallList
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeyCcbs (base name: "editFunctionKeyCcbs")', function() {
      // uncomment below and update the code to test the property editFunctionKeyCcbs
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeyDnd (base name: "editFunctionKeyDnd")', function() {
      // uncomment below and update the code to test the property editFunctionKeyDnd
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeyDtmf (base name: "editFunctionKeyDtmf")', function() {
      // uncomment below and update the code to test the property editFunctionKeyDtmf
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeyForwardCall (base name: "editFunctionKeyForwardCall")', function() {
      // uncomment below and update the code to test the property editFunctionKeyForwardCall
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeyForwardNumberUnconditional (base name: "editFunctionKeyForwardNumberUnconditional")', function() {
      // uncomment below and update the code to test the property editFunctionKeyForwardNumberUnconditional
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeyGenericUrl (base name: "editFunctionKeyGenericUrl")', function() {
      // uncomment below and update the code to test the property editFunctionKeyGenericUrl
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeyGroupLogin (base name: "editFunctionKeyGroupLogin")', function() {
      // uncomment below and update the code to test the property editFunctionKeyGroupLogin
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeyModuleActivation (base name: "editFunctionKeyModuleActivation")', function() {
      // uncomment below and update the code to test the property editFunctionKeyModuleActivation
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeyParkAndOrbit (base name: "editFunctionKeyParkAndOrbit")', function() {
      // uncomment below and update the code to test the property editFunctionKeyParkAndOrbit
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeyPhoneContact (base name: "editFunctionKeyPhoneContact")', function() {
      // uncomment below and update the code to test the property editFunctionKeyPhoneContact
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeyQuickDial (base name: "editFunctionKeyQuickDial")', function() {
      // uncomment below and update the code to test the property editFunctionKeyQuickDial
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeySeperator (base name: "editFunctionKeySeperator")', function() {
      // uncomment below and update the code to test the property editFunctionKeySeperator
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

    it('should have the property editFunctionKeySignalNumber (base name: "editFunctionKeySignalNumber")', function() {
      // uncomment below and update the code to test the property editFunctionKeySignalNumber
      //var instance = new StarfaceRestApi.EditFunctionKey();
      //expect(instance).to.be();
    });

  });

}));
