/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarfaceRestApi);
  }
}(this, function(expect, StarfaceRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarfaceRestApi.ManagedConferenceSummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ManagedConferenceSummary', function() {
    it('should create an instance of ManagedConferenceSummary', function() {
      // uncomment below and update the code to test ManagedConferenceSummary
      //var instance = new StarfaceRestApi.ManagedConferenceSummary();
      //expect(instance).to.be.a(StarfaceRestApi.ManagedConferenceSummary);
    });

    it('should have the property conferenceId (base name: "conferenceId")', function() {
      // uncomment below and update the code to test the property conferenceId
      //var instance = new StarfaceRestApi.ManagedConferenceSummary();
      //expect(instance).to.be();
    });

    it('should have the property isActive (base name: "isActive")', function() {
      // uncomment below and update the code to test the property isActive
      //var instance = new StarfaceRestApi.ManagedConferenceSummary();
      //expect(instance).to.be();
    });

    it('should have the property isReadonly (base name: "isReadonly")', function() {
      // uncomment below and update the code to test the property isReadonly
      //var instance = new StarfaceRestApi.ManagedConferenceSummary();
      //expect(instance).to.be();
    });

    it('should have the property isTerminated (base name: "isTerminated")', function() {
      // uncomment below and update the code to test the property isTerminated
      //var instance = new StarfaceRestApi.ManagedConferenceSummary();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new StarfaceRestApi.ManagedConferenceSummary();
      //expect(instance).to.be();
    });

    it('should have the property startTime (base name: "startTime")', function() {
      // uncomment below and update the code to test the property startTime
      //var instance = new StarfaceRestApi.ManagedConferenceSummary();
      //expect(instance).to.be();
    });

  });

}));
