/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarfaceRestApi);
  }
}(this, function(expect, StarfaceRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarfaceRestApi.PhoneNumber();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PhoneNumber', function() {
    it('should create an instance of PhoneNumber', function() {
      // uncomment below and update the code to test PhoneNumber
      //var instance = new StarfaceRestApi.PhoneNumber();
      //expect(instance).to.be.a(StarfaceRestApi.PhoneNumber);
    });

    it('should have the property assignedGroupAccountId (base name: "assignedGroupAccountId")', function() {
      // uncomment below and update the code to test the property assignedGroupAccountId
      //var instance = new StarfaceRestApi.PhoneNumber();
      //expect(instance).to.be();
    });

    it('should have the property assignedModuleInstanceId (base name: "assignedModuleInstanceId")', function() {
      // uncomment below and update the code to test the property assignedModuleInstanceId
      //var instance = new StarfaceRestApi.PhoneNumber();
      //expect(instance).to.be();
    });

    it('should have the property assignedServiceId (base name: "assignedServiceId")', function() {
      // uncomment below and update the code to test the property assignedServiceId
      //var instance = new StarfaceRestApi.PhoneNumber();
      //expect(instance).to.be();
    });

    it('should have the property assignedUserAccountId (base name: "assignedUserAccountId")', function() {
      // uncomment below and update the code to test the property assignedUserAccountId
      //var instance = new StarfaceRestApi.PhoneNumber();
      //expect(instance).to.be();
    });

    it('should have the property exitCode (base name: "exitCode")', function() {
      // uncomment below and update the code to test the property exitCode
      //var instance = new StarfaceRestApi.PhoneNumber();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new StarfaceRestApi.PhoneNumber();
      //expect(instance).to.be();
    });

    it('should have the property localPrefix (base name: "localPrefix")', function() {
      // uncomment below and update the code to test the property localPrefix
      //var instance = new StarfaceRestApi.PhoneNumber();
      //expect(instance).to.be();
    });

    it('should have the property nationalPrefix (base name: "nationalPrefix")', function() {
      // uncomment below and update the code to test the property nationalPrefix
      //var instance = new StarfaceRestApi.PhoneNumber();
      //expect(instance).to.be();
    });

    it('should have the property _number (base name: "number")', function() {
      // uncomment below and update the code to test the property _number
      //var instance = new StarfaceRestApi.PhoneNumber();
      //expect(instance).to.be();
    });

    it('should have the property numberBlockId (base name: "numberBlockId")', function() {
      // uncomment below and update the code to test the property numberBlockId
      //var instance = new StarfaceRestApi.PhoneNumber();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new StarfaceRestApi.PhoneNumber();
      //expect(instance).to.be();
    });

  });

}));
