/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarfaceRestApi);
  }
}(this, function(expect, StarfaceRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarfaceRestApi.PhoneAssignment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PhoneAssignment', function() {
    it('should create an instance of PhoneAssignment', function() {
      // uncomment below and update the code to test PhoneAssignment
      //var instance = new StarfaceRestApi.PhoneAssignment();
      //expect(instance).to.be.a(StarfaceRestApi.PhoneAssignment);
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instance = new StarfaceRestApi.PhoneAssignment();
      //expect(instance).to.be();
    });

    it('should have the property isIFMC (base name: "isIFMC")', function() {
      // uncomment below and update the code to test the property isIFMC
      //var instance = new StarfaceRestApi.PhoneAssignment();
      //expect(instance).to.be();
    });

    it('should have the property phoneId (base name: "phoneId")', function() {
      // uncomment below and update the code to test the property phoneId
      //var instance = new StarfaceRestApi.PhoneAssignment();
      //expect(instance).to.be();
    });

    it('should have the property phoneName (base name: "phoneName")', function() {
      // uncomment below and update the code to test the property phoneName
      //var instance = new StarfaceRestApi.PhoneAssignment();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new StarfaceRestApi.PhoneAssignment();
      //expect(instance).to.be();
    });

  });

}));
