/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarfaceRestApi);
  }
}(this, function(expect, StarfaceRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarfaceRestApi.RedirectMailboxDestination();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RedirectMailboxDestination', function() {
    it('should create an instance of RedirectMailboxDestination', function() {
      // uncomment below and update the code to test RedirectMailboxDestination
      //var instance = new StarfaceRestApi.RedirectMailboxDestination();
      //expect(instance).to.be.a(StarfaceRestApi.RedirectMailboxDestination);
    });

    it('should have the property mailboxId (base name: "mailboxId")', function() {
      // uncomment below and update the code to test the property mailboxId
      //var instance = new StarfaceRestApi.RedirectMailboxDestination();
      //expect(instance).to.be();
    });

    it('should have the property redirectDestinationType (base name: "redirectDestinationType")', function() {
      // uncomment below and update the code to test the property redirectDestinationType
      //var instance = new StarfaceRestApi.RedirectMailboxDestination();
      //expect(instance).to.be();
    });

  });

}));
