/**
 * STARFACE Rest Api
 * A Rest API for STARFACE
 *
 * OpenAPI spec version: 6.7.0.22
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarfaceRestApi);
  }
}(this, function(expect, StarfaceRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarfaceRestApi.Voicemailbox();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Voicemailbox', function() {
    it('should create an instance of Voicemailbox', function() {
      // uncomment below and update the code to test Voicemailbox
      //var instance = new StarfaceRestApi.Voicemailbox();
      //expect(instance).to.be.a(StarfaceRestApi.Voicemailbox);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new StarfaceRestApi.Voicemailbox();
      //expect(instance).to.be();
    });

    it('should have the property maximumDuration (base name: "maximumDuration")', function() {
      // uncomment below and update the code to test the property maximumDuration
      //var instance = new StarfaceRestApi.Voicemailbox();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new StarfaceRestApi.Voicemailbox();
      //expect(instance).to.be();
    });

    it('should have the property noRecord (base name: "noRecord")', function() {
      // uncomment below and update the code to test the property noRecord
      //var instance = new StarfaceRestApi.Voicemailbox();
      //expect(instance).to.be();
    });

    it('should have the property _number (base name: "number")', function() {
      // uncomment below and update the code to test the property _number
      //var instance = new StarfaceRestApi.Voicemailbox();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new StarfaceRestApi.Voicemailbox();
      //expect(instance).to.be();
    });

    it('should have the property voicemailGroups (base name: "voicemailGroups")', function() {
      // uncomment below and update the code to test the property voicemailGroups
      //var instance = new StarfaceRestApi.Voicemailbox();
      //expect(instance).to.be();
    });

    it('should have the property voicemailUsers (base name: "voicemailUsers")', function() {
      // uncomment below and update the code to test the property voicemailUsers
      //var instance = new StarfaceRestApi.Voicemailbox();
      //expect(instance).to.be();
    });

  });

}));
